<?xml version="1.0" encoding="UTF-8"?>
<CONFIG>
  <Makefile Value="2"/>
  <Params Value=" -Fuclient;client/3.0/firebird;client/2.5;.;client/3.0;../../packager/units/$(CPU_TARGET)-$(OS_TARGET) -Ficlient/3.0/firebird;client/include;include  -MObjFPC -Scghi -O3 -l -vewnhibq fbintf.pas"/>
</CONFIG>
