[requires]
packages=fcl-res
libc=y

[compiler]
options= -MObjFPC -Scghi -Cg -Cr -O1 -g -gl -gh -l -vewnhibq -dUseCThreads -dFIREBIRD3APIONLY

unittargetdir=testunits/$(CPU_TARGET)-$(OS_TARGET)
includedir=$(FBINTFROOT)/client/3.0/firebird $(FBINTFROOT)/client/include 
unitdir=$(FBINTFROOT)/client $(FBINTFROOT)/client/3.0/firebird  . $(FBINTFROOT)/client/3.0 $(FBINTFROOT)/udr/source $(FBINTFROOT) 

[target]
programs=fbudrtests 



