Update EMPLOYEE Set PHONE_EXT = '999' Where EMP_NO = 2;
Select PHONE_EXT,PREVIOUS_PHONE_EXT FROM EMPLOYEE Where EMP_NO = 2;
Update EMPLOYEE Set PHONE_EXT = '250' Where EMP_NO = 2;
Select PHONE_EXT,PREVIOUS_PHONE_EXT FROM EMPLOYEE Where EMP_NO = 2;

